M48
; DRILL file {KiCad 9.0.0} date 2025-03-29T14:14:05-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-29T14:14:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.540
%
G90
G05
T1
X121.05Y-99.075
X127.85Y-99.075
T2
X162.56Y-99.06
X162.56Y-116.84
M30
